### PR TITLE
Don't bail out if one service/ingress has an issue plus fixes for ingress function

### PR DESCRIPTION
**Pull request by cknowles**
Updated version of https://github.com/fairfaxmedia/area53/pull/3.

For instance something like `Aws::Route53::Errors::InvalidChangeBatch: FATAL problem: DomainLabelTooLong (Domain label is too long)` will currently cause all watch processing to stop.

Also re-adds the DNS TTL configuration (optional) and adds some information on Ingress configuration.

### CODE REVIEW

**Comment by cknowles** [comment]
Any chance of a review and merge?

**Comment by alex-mcd** [comment]
Apologies for the delay, do you have access to the bitbucket [repo](https://bitbucket.org/fairfax/area-53)? All changes should take place there as well.

**Comment by cknowles** [comment]
@alex-mcd I do not have access, is it public or private? Just in case it's not clear - I'm a user and contributor of area53 rather than affiliated with Fairfax.

**Comment by alex-mcd** [comment]
Ahh, sorry. Your picture looks just like someone who works near me so I made the assumption. I'll make sure your change is added internally so it doesn't get overwritten in future updates

**Comment by cknowles** [comment]
@alex-mcd who's that :) ? Sure ok, thank you! Do you happen to know if there are plans to push the image to docker hub? I've got it publishing and can see `songsterr` [is doing the same](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=area53&starCount=0). Happy to keep it like that as it's on the free plan, just might be better if fairfax controls it.

**Pull request merged**
